apiVersion: v2
name: traefikee
description: |
  Traefik Enterprise is a unified cloud-native networking solution that brings API management, ingress control, and
  Service Mesh all together in one simple control plane. Traefik Enterprise eases microservices networking complexity
  for developers and operations teams across the organization.
icon: https://doc.traefik.io/traefik-enterprise/assets/images/logo-traefik-enterprise-logo.svg
# Because of https://github.com/helm/helm/issues/3810 the pre-release version suffix has to be define.
# This allows the installation on Kubernetes cluster with a pre-release version (e.g. v1.19.9-gke.1900)
kubeVersion: ">= 1.14.0-0"
version: 3.0.1
# renovate: image=docker.io/traefik/traefikee
appVersion: v2.10.7
type: application
home: https://traefik.io/traefik-enterprise/
maintainers:
  - name: darkweaver87
  - name: mloiseleur
  - name: mmatur
  - name: NEwa-05
  - name: sdelicata
  - name: kevinpollet
keywords:
  - traefikee
  - traefik-enterprise
annotations:
  artifacthub.io/changes: |
    - "chore: release v3.0.1 with Traefik Enterprise v2.10.6"
